### ISSUE TITLE
Ошибка при вызове apache_request_headers()

### ISSUE THREAD

**Issue by nikservik** [albakov/LaravelCloudPayments#1]
В Notifications.php строка 94
$headers = apache_request_headers();

Без Апача говорит, что такая функция не существует. 
Можно использовать стандартный интерфейс Request.

Я у себя эти две строки
$headers = apache_request_headers();
$secretCloudPayments = isset($headers['Content-Hmac']) ? $headers['Content-Hmac'] : '';

заменил на 
$secretCloudPayments = $request->header('Content-Hmac');

Поправь, пожалуйста, если время есть.

P.S. За пакет большое спасибо!

**Comment by albakov** [comment]
Поправил ;)
