### ISSUE TITLE
Ошибка приведения типа в subscriptionsInfo()

### ISSUE THREAD

**Issue by nikservik** [albakov/LaravelCloudPayments#2]
Раз уж ты на связи, брошу еще один баг :)

В LaravelCloudPayments.php в методе subscriptionsInfo() параметр $id приводится к типу int, а у них в API идентификаторы строчные. 
Строка 228 в идеале: 
            'data' => ['Id' => (string) $id],

**Comment by albakov** [comment]
Внес правки!
