### ISSUE TITLE
Интеграция виджета будет или не стоит того?

### ISSUE THREAD

**Issue by ghost** [albakov/LaravelCloudPayments#8]
субж.

**Comment by daaner** [comment]
не стоит! он подключается в 2 клика, и в зависимости от своего фронта он нужен разный

**Comment by albakov** [comment]
Не стоит того. По сути нужен только обработчик уведомлений (https://github.com/albakov/LaravelCloudPayments/blob/master/src/Notifications.php) и то не всегда.
